# Working on Real Project with Python

# Weather Dataset Analysis using Pandas :-

Here, The Weather Dataset is a time-series data set with 
per-hour information about the weather conditions at a 
particular location. It records Temperature, Dew Point 
Temperature, Relative Humidity, Wind Speed, Visibility, 
Pressure, and Conditions.

This data is available as a CSV file. We are going to analyze
 this data set using the Pandas DataFrame.


Q1. To show top-5 records of the dataset?

Q2. To show bottom-5 records of dataset?

Q3. To show the No. of Rows and Columns?

Q4. To show each Column Name?

Q5. To show the data-type of each column?

Q6. To show indexes, columns, data-types of each column, memory at once?

Q7. Find all the unique 'Wind Speed' values in the data?

Q8. Find the number of times when the 'Weather is exactly Clear' ?

Q9. Find the number of times when the 'Wind Speed was exactly 4 km/h' ?

Q10. Find out all the Null Values in the data?

Q11. Rename the column name 'Weather' of the data to 'Weather Condition' ?

Q12. What is the mean 'Visibility' ?

Q13. What is the Standard Deviation of 'Pressure' in this data?

Q14. Whats is the Variance of 'Relative Humidity' in this data ?

Q15. Find all instances when 'Snow' was recorded?

Q16. Find all instances when 'Wind Speed is above 24' and 'Visibility is 25' ?

Q17. What is the Mean value of each column against each 'Weather Conditon' ?

Q18. What is the Minimum & Maximum value of each column against each 'Weather Conditon' ?

Q19. Show all the Records where Weather Condition is Fog ?

Q20. Find all instances when 'Weather is Clear' or 'Visibility is above 40' ?

Q21. Find all instances when : A. 'Weather is Clear' and 'Relative Humidity is greater than 50' .
        or  B. 'Visibility is above 40' .

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('dataset/Weather.csv')
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

# How to Analyze DataFrame ?

# .head()
It show the first N rows in the data(by deafault,N=5)

In [3]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

# .shape
It shows the total no of rows and no of columns of the dataframe

In [4]:
df.shape

(8784, 8)

# .index
The attribute provides the index of the dataframe

In [5]:
df.index

RangeIndex(start=0, stop=8784, step=1)

# .columns
It show the name of each column

In [6]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

# .dtypes
It show the data-type of each column

In [7]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

# .unique()
In a column, it shows all the unique values. It can be applied on a single column only, not on the
whole dataframe.

In [8]:
df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

# .nunique
It show the total no. of unique values in each column. It can be applied on a singlecolumn as well as on whole dataframe.

In [9]:
df.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

# .count
It shows the total no. of non-null values in each column. It can be appliedon a single
column as well as on whole dataframe.

In [10]:
df.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

# .value_counts
In a column, it shows all the unique values with their count. It can be applied on single column only.

In [11]:
df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

# .info()
Provides basic information about the dataframe.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [13]:
#Q1. To show top-5 records of the dataset?
df.head(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [14]:
#Q2. To show bottom-5 records of dataset?
df.tail(5)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [15]:
#Q3. To show the No. of Rows and Columns?
df.shape

(8784, 8)

In [16]:
#Q4. To show each Column Name?
df.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [17]:
df.columns.dtype

dtype('O')

In [18]:
#Q6. To show indexes, columns, data-types of each column, memory at once?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [22]:
#Q7. Find all the unique 'Wind Speed' values in the data?
df['Wind_Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [23]:
df['Wind_Speed_km/h'].nunique()

34

In [24]:
#Q8. Find the number of times when the 'Weather is exactly Clear' ?
#Filtering
df[df.Weather=='Clear']

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [58]:
 #groupby
df.groupby('Weather_Condition').get_group('Clear')

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [ ]:
df.columns=df.columns.str.replace(" ","_")

In [26]:
df.columns

Index(['Date/Time', 'Temp_C', 'Dew_Point_Temp_C', 'Rel_Hum_%',
       'Wind_Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [27]:
#Q9. Find the number of times when the 'Wind Speed was exactly 4 km/h' ?#
df[df['Wind_Speed_km/h'] == 4]

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

In [28]:
#Q10. Find out all the Null Values in the data?
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew_Point_Temp_C    0
Rel_Hum_%           0
Wind_Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [29]:
df.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew_Point_Temp_C    8784
Rel_Hum_%           8784
Wind_Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [30]:
#Q11. Rename the column name 'Weather' of the data to 'Weather Condition' ?
df.rename(columns={'Weather':'Weather Condition'},inplace=True)
df

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [31]:
df.describe()

,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

In [32]:
#Q12. What is the mean 'Visibility' ?
df.Visibility_km.mean()

27.664446721311478

In [33]:
#Q13. What is the Standard Deviation of 'Pressure' in this data?
df.Press_kPa.std()

0.8440047459486474

In [34]:
#Q14. Whats is the Variance of 'Relative Humidity' in this data
df['Rel_Hum_%'].var()

286.2485501984998

In [35]:
#Q15. Find all instances when 'Snow' was recorded?
df[df['Weather Condition'] =='Snow']

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,1/3/2012 7:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,1/4/2012 12:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,1/4/2012 14:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,1/4/2012 15:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,1/4/2012 16:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [36]:
#str contains
df[df['Weather Condition'].str.contains('Snow')].tail(50)

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather Condition
8680,12/27/2012 16:00,-4.5,-6.2,88,37,2.0,100.44,"Snow,Blowing Snow"
8681,12/27/2012 17:00,-4.2,-5.9,88,32,3.2,100.47,"Snow,Blowing Snow"
8682,12/27/2012 18:00,-4.0,-5.7,88,28,8.0,100.49,"Snow,Blowing Snow"
8683,12/27/2012 19:00,-3.9,-5.6,88,26,9.7,100.52,"Snow,Blowing Snow"
8684,12/27/2012 20:00,-3.7,-5.3,89,37,16.1,100.58,Snow
8685,12/27/2012 21:00,-3.7,-4.8,92,24,4.8,100.62,"Freezing Drizzle,Snow"
8686,12/27/2012 22:00,-3.8,-4.6,94,20,4.8,100.65,"Freezing Drizzle,Snow"
8687,12/27/2012 23:00,-4.0,-5.6,89,24,9.7,100.70,Snow
8688,12/28/2012 0:00,-4.2,-5.7,89,19,8.0,100.78,"Freezing Drizzle,Snow"
8689,12/28/2012 1:00,-4.4,-6.6,85,15,6.4,100.83,"Freezing Drizzle,Snow"
8690,12/28/2012 2:00,-4.3,-6.3,86,11,12.9,100.93,"Freezing Drizzle,Snow"
8691,12/28/2012 3:00,-4.6,-5.9,91,13,4.0,101.01,Snow
8692,12/28/2012 4:00,-4.9,-5.9,93,9,9.7,101.00,Snow
8723,12/29/2012 11:00,-10.9,-12.2,90,7,6.4,101.09,"Snow Showers,Fog"
8724,12/29/2012 12:00,-10.5,-11.6,92,11,8.0,100.93,"Snow Showers,Fog"
8725,12/29/2012 13:00,-10.0,-11.1,92,22,9.7,100.63,"Snow Showers,Fog"
8726,12/29/2012 14:00,-9.3,-10.5,91,22,4.8,100.60,"Snow,Fog"
8727,12/29/2012 15:00,-8.8,-10.0,91,20,1.2,100.55,"Snow,Fog"
8728,12/29/2012 16:00,-8.5,-9.9,90,24,1.2,100.49,"Snow,Fog"
8729,12/29/2012 17:00,-9.0,-10.4,90,19,2.4,100.46,"Snow,Fog"
8730,12/29/2012 18:00,-9.3,-10.9,88,26,6.4,100.38,"Snow,Fog"
8731,12/29/2012 19:00,-9.5,-11.2,87,26,3.2,100.33,"Snow,Fog"
8732,12/29/2012 20:00,-9.7,-11.6,86,24,9.7,100.25,"Snow,Fog"
8733,12/29/2012 21:00,-9.8,-11.8,85,24,8.0,100.24,"Snow,Fog"
8734,12/29/2012 22:00,-10.1,-11.6,89,15,2.4,100.20,"Snow,Fog"
8735,12/29/2012 23:00,-10.0,-12.0,85,20,6.4,100.19,"Snow,Fog"
8736,12/30/2012 0:00,-9.6,-11.3,87,13,3.2,100.23,"Snow,Fog"
8737,12/30/2012 1:00,-9.4,-10.5,92,9,2.4,100.22,"Snow,Fog"
8738,12/30/2012 2:00,-9.3,-10.4,92,9,4.0,100.28,"Snow,Fog"
8739,12/30/2012 3:00,-9.1,-10.4,90,11,3.6,100.30,"Snow,Fog"
8740,12/30/2012 4:00,-9.3,-10.6,90,13,9.7,100.28,"Snow,Fog"
8741,12/30/2012 5:00,-9.1,-10.4,90,11,4.0,100.32,"Snow,Fog"
8742,12/30/2012 6:00,-9.3,-10.8,89,17,8.0,100.39,"Snow,Fog"
8767,12/31/2012 7:00,-9.3,-11.3,85,0,19.3,101.19,Snow Showers
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8771,12/31/2012 11:00,-6.7,-7.9,91,9,9.7,100.93,Snow
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow
8774,12/31/2012 14:00,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,12/31/2012 15:00,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,12/31/2012 16:00,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,12/31/2012 17:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,12/31/2012 18:00,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [37]:
#Q16. Find all instances when 'Wind Speed is above 24' and 'Visibility is 25' ?
df[(df['Wind_Speed_km/h']>24) & (df['Visibility_km']==25) ]

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [41]:
df.columns=df.columns.str.replace(" ","_")

In [54]:
df.head(1)

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [57]:
#Q17. What is the Mean value of each column against each 'Weather Conditon' ?
df.groupby('Weather_Condition').mean()

TypeError: Could not convert 1/3/2012 19:001/5/2012 18:001/5/2012 19:001/5/2012 20:001/5/2012 21:001/11/2012 1:001/11/2012 2:001/11/2012 3:001/11/2012 4:001/15/2012 8:001/15/2012 15:001/15/2012 16:001/15/2012 17:001/15/2012 18:001/15/2012 19:001/15/2012 20:001/15/2012 21:001/15/2012 22:001/15/2012 23:001/16/2012 0:001/16/2012 1:001/16/2012 2:001/16/2012 3:001/16/2012 4:001/16/2012 5:001/16/2012 6:001/18/2012 17:001/18/2012 18:001/18/2012 19:001/18/2012 20:001/18/2012 21:001/18/2012 22:001/18/2012 23:001/19/2012 0:001/19/2012 1:001/19/2012 2:001/19/2012 3:001/19/2012 4:001/19/2012 5:001/19/2012 6:001/19/2012 7:001/19/2012 8:001/19/2012 9:001/20/2012 9:001/20/2012 11:001/20/2012 12:001/20/2012 13:001/21/2012 14:001/21/2012 15:001/21/2012 16:001/21/2012 17:001/21/2012 18:001/21/2012 19:001/21/2012 20:001/21/2012 21:001/21/2012 22:001/22/2012 0:001/22/2012 1:001/22/2012 2:001/22/2012 21:001/26/2012 1:001/26/2012 2:001/26/2012 3:001/26/2012 4:001/26/2012 5:001/26/2012 6:001/26/2012 8:001/29/2012 23:001/30/2012 0:001/30/2012 2:001/30/2012 3:001/30/2012 4:001/30/2012 5:001/30/2012 6:001/30/2012 7:001/30/2012 8:001/30/2012 14:002/4/2012 6:002/4/2012 7:002/4/2012 8:002/4/2012 9:002/4/2012 11:002/4/2012 16:002/4/2012 17:002/4/2012 18:002/4/2012 19:002/4/2012 20:002/4/2012 21:002/4/2012 22:002/4/2012 23:002/5/2012 0:002/5/2012 1:002/5/2012 2:002/5/2012 3:002/5/2012 4:002/5/2012 5:002/5/2012 6:002/5/2012 7:002/5/2012 8:002/5/2012 9:002/7/2012 13:002/7/2012 14:002/7/2012 15:002/7/2012 16:002/7/2012 17:002/7/2012 18:002/7/2012 19:002/7/2012 20:002/7/2012 21:002/7/2012 22:002/7/2012 23:002/8/2012 0:002/8/2012 1:002/8/2012 2:002/8/2012 3:002/8/2012 4:002/8/2012 5:002/8/2012 12:002/8/2012 13:002/8/2012 19:002/8/2012 20:002/8/2012 23:002/9/2012 0:002/9/2012 1:002/9/2012 2:002/9/2012 3:002/9/2012 4:002/9/2012 5:002/9/2012 6:002/9/2012 8:002/9/2012 11:002/9/2012 12:002/9/2012 13:002/9/2012 14:002/9/2012 15:002/9/2012 16:002/9/2012 17:002/9/2012 18:002/9/2012 19:002/9/2012 20:002/9/2012 21:002/9/2012 22:002/9/2012 23:002/10/2012 0:002/10/2012 1:002/10/2012 2:002/10/2012 3:002/10/2012 4:002/10/2012 5:002/10/2012 6:002/11/2012 18:002/11/2012 19:002/11/2012 20:002/11/2012 21:002/11/2012 22:002/11/2012 23:002/12/2012 0:002/12/2012 2:002/18/2012 20:002/18/2012 21:002/18/2012 22:002/18/2012 23:002/19/2012 0:002/19/2012 3:002/19/2012 6:002/19/2012 14:002/19/2012 15:002/19/2012 16:002/19/2012 17:002/19/2012 18:002/19/2012 19:002/19/2012 20:002/19/2012 21:002/19/2012 22:002/19/2012 23:002/20/2012 0:002/20/2012 1:002/20/2012 2:002/20/2012 3:002/20/2012 4:002/20/2012 5:002/20/2012 6:002/20/2012 7:002/20/2012 17:002/20/2012 18:002/20/2012 19:002/20/2012 21:002/20/2012 22:002/20/2012 23:002/21/2012 0:002/21/2012 1:002/21/2012 2:002/21/2012 3:002/21/2012 4:002/23/2012 19:002/23/2012 20:002/23/2012 21:002/23/2012 22:002/23/2012 23:002/24/2012 0:002/24/2012 1:002/24/2012 2:002/26/2012 2:002/26/2012 5:002/26/2012 6:002/26/2012 7:002/26/2012 10:002/26/2012 11:002/26/2012 12:002/28/2012 9:002/28/2012 10:002/28/2012 11:002/28/2012 18:002/28/2012 19:002/28/2012 20:002/28/2012 21:002/28/2012 22:002/28/2012 23:002/29/2012 0:002/29/2012 1:002/29/2012 3:002/29/2012 5:002/29/2012 6:003/5/2012 2:003/5/2012 3:003/5/2012 4:003/5/2012 5:003/5/2012 19:003/5/2012 21:003/5/2012 22:003/5/2012 23:003/6/2012 0:003/6/2012 1:003/6/2012 2:003/6/2012 3:003/6/2012 4:003/6/2012 5:003/6/2012 6:003/6/2012 7:003/6/2012 8:003/6/2012 9:003/7/2012 9:003/7/2012 10:003/9/2012 7:003/9/2012 8:003/9/2012 9:003/10/2012 12:003/11/2012 7:003/11/2012 8:003/11/2012 10:003/11/2012 11:003/11/2012 12:003/11/2012 13:003/11/2012 14:003/11/2012 15:003/11/2012 16:003/11/2012 17:003/11/2012 18:003/11/2012 19:003/11/2012 20:003/11/2012 22:003/11/2012 23:003/12/2012 0:003/12/2012 5:003/12/2012 6:003/18/2012 3:003/18/2012 4:003/18/2012 5:003/18/2012 6:003/18/2012 11:003/18/2012 12:003/18/2012 20:003/19/2012 1:003/19/2012 2:003/19/2012 3:003/19/2012 4:003/19/2012 5:003/19/2012 21:003/19/2012 22:003/19/2012 23:003/20/2012 0:003/20/2012 1:003/20/2012 2:003/20/2012 3:003/20/2012 4:003/20/2012 5:003/20/2012 6:003/20/2012 7:003/20/2012 8:003/20/2012 11:003/20/2012 12:003/20/2012 13:003/20/2012 14:003/20/2012 15:003/20/2012 16:003/20/2012 17:003/20/2012 18:003/20/2012 19:003/20/2012 20:003/20/2012 21:003/20/2012 22:003/20/2012 23:003/21/2012 0:003/21/2012 1:003/21/2012 2:003/21/2012 3:003/21/2012 4:003/21/2012 5:003/21/2012 8:003/21/2012 9:003/21/2012 10:003/21/2012 11:003/21/2012 12:003/21/2012 13:003/21/2012 14:003/21/2012 15:003/21/2012 16:003/21/2012 17:003/21/2012 18:003/21/2012 19:003/21/2012 20:003/21/2012 21:003/21/2012 22:003/21/2012 23:003/22/2012 0:003/22/2012 1:003/22/2012 2:003/22/2012 3:003/22/2012 4:003/22/2012 5:003/22/2012 23:003/23/2012 4:003/23/2012 5:003/23/2012 6:003/23/2012 7:003/23/2012 8:003/23/2012 9:003/23/2012 10:003/23/2012 11:003/26/2012 4:003/26/2012 5:003/26/2012 6:003/26/2012 16:003/26/2012 17:003/26/2012 18:003/26/2012 19:003/26/2012 20:003/26/2012 21:003/26/2012 22:003/26/2012 23:003/27/2012 0:003/27/2012 1:003/27/2012 2:003/27/2012 3:003/27/2012 4:003/27/2012 5:003/27/2012 6:003/27/2012 7:003/27/2012 8:003/27/2012 9:003/27/2012 10:003/27/2012 11:003/27/2012 12:003/30/2012 2:003/30/2012 5:003/30/2012 6:003/30/2012 7:003/30/2012 8:003/30/2012 9:003/30/2012 10:003/31/2012 11:003/31/2012 12:003/31/2012 13:003/31/2012 19:003/31/2012 20:003/31/2012 21:003/31/2012 22:003/31/2012 23:004/1/2012 0:004/1/2012 1:004/1/2012 2:004/1/2012 3:004/2/2012 2:004/2/2012 5:004/2/2012 6:004/2/2012 7:004/2/2012 8:004/2/2012 9:004/2/2012 10:004/2/2012 11:004/2/2012 12:004/2/2012 13:004/2/2012 14:004/2/2012 15:004/2/2012 16:004/2/2012 18:004/2/2012 19:004/2/2012 20:004/2/2012 21:004/2/2012 22:004/2/2012 23:004/3/2012 0:004/3/2012 1:004/3/2012 2:004/3/2012 3:004/3/2012 4:004/3/2012 5:004/3/2012 6:004/3/2012 7:004/3/2012 8:004/3/2012 9:004/3/2012 10:004/6/2012 7:004/6/2012 8:004/6/2012 9:004/6/2012 11:004/6/2012 13:004/12/2012 22:004/12/2012 23:004/13/2012 0:004/13/2012 1:004/13/2012 2:004/13/2012 3:004/13/2012 4:004/13/2012 5:004/13/2012 6:004/14/2012 0:004/14/2012 1:004/14/2012 2:004/15/2012 3:004/15/2012 4:004/15/2012 5:004/18/2012 0:004/18/2012 1:004/18/2012 2:004/18/2012 3:004/18/2012 4:004/18/2012 5:004/18/2012 6:004/18/2012 7:004/18/2012 8:004/18/2012 9:004/18/2012 10:004/18/2012 11:004/19/2012 1:004/19/2012 2:004/19/2012 21:004/20/2012 1:004/26/2012 3:004/26/2012 4:004/26/2012 5:004/26/2012 6:004/28/2012 18:004/28/2012 19:004/28/2012 21:004/29/2012 10:004/29/2012 11:004/29/2012 12:004/29/2012 13:004/29/2012 14:004/29/2012 15:004/29/2012 17:004/29/2012 18:004/29/2012 19:004/29/2012 22:004/29/2012 23:004/30/2012 0:004/30/2012 1:004/30/2012 2:004/30/2012 3:004/30/2012 4:005/5/2012 16:005/5/2012 17:005/6/2012 23:005/7/2012 0:005/7/2012 1:005/7/2012 2:005/7/2012 3:005/7/2012 4:005/7/2012 5:005/7/2012 6:005/7/2012 7:005/7/2012 8:005/7/2012 9:005/7/2012 10:005/7/2012 21:005/11/2012 18:005/11/2012 19:005/11/2012 20:005/11/2012 21:005/11/2012 22:005/11/2012 23:005/12/2012 0:005/12/2012 1:005/12/2012 2:005/12/2012 3:005/12/2012 4:005/12/2012 5:005/12/2012 6:005/12/2012 7:005/12/2012 8:005/12/2012 9:005/12/2012 10:005/13/2012 18:005/13/2012 21:005/13/2012 22:005/13/2012 23:005/14/2012 0:005/14/2012 1:005/14/2012 2:005/14/2012 3:005/15/2012 22:005/15/2012 23:005/16/2012 0:005/16/2012 1:005/16/2012 2:005/16/2012 3:005/17/2012 2:005/17/2012 3:005/17/2012 4:005/17/2012 5:005/17/2012 6:005/17/2012 18:005/17/2012 19:005/17/2012 21:005/17/2012 22:005/17/2012 23:005/18/2012 1:005/18/2012 2:005/18/2012 3:005/18/2012 4:005/18/2012 21:005/19/2012 22:005/19/2012 23:005/20/2012 0:005/20/2012 1:005/20/2012 2:005/20/2012 3:005/23/2012 0:005/23/2012 20:005/23/2012 21:005/23/2012 22:005/23/2012 23:005/24/2012 0:005/24/2012 1:005/24/2012 2:005/24/2012 3:005/24/2012 4:005/24/2012 10:005/24/2012 11:005/24/2012 20:005/24/2012 21:005/24/2012 22:005/24/2012 23:005/25/2012 0:005/25/2012 1:005/25/2012 2:005/25/2012 9:005/25/2012 23:005/26/2012 0:005/26/2012 1:005/26/2012 2:005/26/2012 3:005/26/2012 4:005/26/2012 6:005/26/2012 7:005/26/2012 8:005/26/2012 9:005/26/2012 11:005/27/2012 0:005/27/2012 1:005/30/2012 9:005/30/2012 11:005/30/2012 13:005/30/2012 14:005/30/2012 16:005/30/2012 17:005/31/2012 21:005/31/2012 22:005/31/2012 23:006/1/2012 0:006/1/2012 1:006/5/2012 9:006/7/2012 2:006/7/2012 3:006/8/2012 1:006/8/2012 2:006/8/2012 21:006/8/2012 22:006/8/2012 23:006/9/2012 0:006/9/2012 1:006/9/2012 2:006/9/2012 3:006/9/2012 22:006/10/2012 1:006/10/2012 2:006/10/2012 4:006/10/2012 21:006/10/2012 23:006/11/2012 0:006/13/2012 19:006/13/2012 20:006/13/2012 21:006/13/2012 22:006/13/2012 23:006/14/2012 0:006/14/2012 1:006/14/2012 2:006/14/2012 3:006/14/2012 4:006/14/2012 5:006/14/2012 6:006/14/2012 7:006/14/2012 8:006/14/2012 9:006/14/2012 10:006/14/2012 11:006/14/2012 12:006/14/2012 13:006/14/2012 14:006/14/2012 15:006/14/2012 16:006/14/2012 17:006/14/2012 18:006/14/2012 19:006/14/2012 20:006/14/2012 21:006/14/2012 22:006/14/2012 23:006/15/2012 0:006/15/2012 1:006/15/2012 2:006/15/2012 3:006/15/2012 4:006/15/2012 5:006/15/2012 6:006/15/2012 7:006/15/2012 23:006/16/2012 0:006/16/2012 2:006/16/2012 21:006/17/2012 3:006/19/2012 2:006/19/2012 3:006/20/2012 2:006/20/2012 13:006/20/2012 14:006/20/2012 22:006/21/2012 1:006/21/2012 10:006/21/2012 18:006/21/2012 19:006/21/2012 23:006/22/2012 0:006/23/2012 20:006/23/2012 21:006/23/2012 23:006/24/2012 0:006/24/2012 1:006/24/2012 2:006/24/2012 3:006/24/2012 4:006/24/2012 5:006/24/2012 6:006/24/2012 7:006/24/2012 8:006/24/2012 9:006/24/2012 10:006/29/2012 10:006/30/2012 0:006/30/2012 1:006/30/2012 2:006/30/2012 3:006/30/2012 4:007/3/2012 1:007/3/2012 2:007/3/2012 3:007/3/2012 4:007/3/2012 5:007/3/2012 6:007/3/2012 7:007/3/2012 8:007/4/2012 22:007/4/2012 23:007/5/2012 0:007/5/2012 20:007/5/2012 21:007/5/2012 22:007/5/2012 23:007/6/2012 2:007/6/2012 3:007/6/2012 4:007/8/2012 4:007/8/2012 9:007/8/2012 10:007/8/2012 11:007/8/2012 12:007/8/2012 20:007/8/2012 21:007/8/2012 22:007/8/2012 23:007/9/2012 0:007/9/2012 1:007/9/2012 2:007/9/2012 7:007/9/2012 8:007/9/2012 9:007/9/2012 10:007/9/2012 11:007/9/2012 12:007/9/2012 20:007/9/2012 22:007/10/2012 0:007/10/2012 1:007/10/2012 2:007/10/2012 3:007/10/2012 4:007/10/2012 20:007/10/2012 22:007/10/2012 23:007/11/2012 0:007/11/2012 1:007/11/2012 2:007/11/2012 3:007/11/2012 4:007/11/2012 5:007/11/2012 6:007/11/2012 7:007/11/2012 8:007/11/2012 9:007/11/2012 23:007/12/2012 0:007/12/2012 1:007/12/2012 2:007/12/2012 3:007/13/2012 4:007/13/2012 15:007/13/2012 16:007/13/2012 18:007/13/2012 22:007/13/2012 23:007/14/2012 0:007/14/2012 1:007/14/2012 2:007/14/2012 3:007/14/2012 4:007/14/2012 21:007/14/2012 22:007/14/2012 23:007/15/2012 0:007/15/2012 1:007/15/2012 3:007/18/2012 3:007/18/2012 21:007/18/2012 22:007/18/2012 23:007/19/2012 0:007/19/2012 1:007/19/2012 2:007/19/2012 3:007/19/2012 7:007/20/2012 0:007/20/2012 1:007/20/2012 2:007/20/2012 3:007/20/2012 4:007/20/2012 5:007/20/2012 21:007/20/2012 22:007/20/2012 23:007/21/2012 0:007/21/2012 1:007/21/2012 2:007/21/2012 3:007/21/2012 4:007/21/2012 5:007/21/2012 6:007/21/2012 7:007/22/2012 22:007/24/2012 23:007/25/2012 0:007/25/2012 1:007/25/2012 2:007/25/2012 3:007/25/2012 4:007/25/2012 5:007/25/2012 6:007/25/2012 7:007/25/2012 8:007/25/2012 9:007/25/2012 10:007/29/2012 0:007/29/2012 1:007/29/2012 2:007/29/2012 23:007/30/2012 2:007/30/2012 3:007/30/2012 8:007/30/2012 21:007/30/2012 22:007/31/2012 3:007/31/2012 7:007/31/2012 8:008/1/2012 1:008/2/2012 5:008/2/2012 6:008/3/2012 8:008/3/2012 17:008/3/2012 18:008/3/2012 19:008/3/2012 20:008/3/2012 21:008/3/2012 22:008/3/2012 23:008/4/2012 0:008/4/2012 11:008/4/2012 12:008/4/2012 13:008/4/2012 14:008/4/2012 15:008/4/2012 16:008/4/2012 17:008/4/2012 20:008/4/2012 23:008/5/2012 0:008/5/2012 1:008/5/2012 2:008/5/2012 23:008/6/2012 0:008/6/2012 2:008/6/2012 3:008/6/2012 4:008/6/2012 5:008/6/2012 6:008/6/2012 19:008/6/2012 20:008/6/2012 21:008/6/2012 22:008/6/2012 23:008/7/2012 0:008/7/2012 1:008/7/2012 2:008/7/2012 3:008/7/2012 4:008/7/2012 5:008/7/2012 6:008/8/2012 3:008/8/2012 4:008/8/2012 6:008/8/2012 7:008/13/2012 0:008/13/2012 1:008/15/2012 21:008/16/2012 0:008/16/2012 18:008/17/2012 1:008/17/2012 2:008/17/2012 3:008/17/2012 5:008/18/2012 1:008/18/2012 20:008/18/2012 21:008/18/2012 23:008/19/2012 0:008/19/2012 1:008/19/2012 2:008/19/2012 3:008/19/2012 4:008/19/2012 8:008/19/2012 22:008/20/2012 2:008/20/2012 9:008/20/2012 16:008/20/2012 20:008/22/2012 15:008/22/2012 21:008/23/2012 7:008/23/2012 20:008/24/2012 8:008/25/2012 10:008/25/2012 13:008/25/2012 21:008/25/2012 22:008/25/2012 23:008/26/2012 0:008/26/2012 1:008/26/2012 2:008/26/2012 3:008/26/2012 4:008/26/2012 5:008/26/2012 6:008/26/2012 7:008/29/2012 0:008/29/2012 3:008/29/2012 4:008/29/2012 5:008/29/2012 6:008/29/2012 7:008/29/2012 8:008/29/2012 9:008/29/2012 10:008/29/2012 11:008/29/2012 13:008/29/2012 14:008/29/2012 18:008/29/2012 19:008/29/2012 20:008/29/2012 21:008/29/2012 22:008/29/2012 23:008/30/2012 0:008/30/2012 1:008/30/2012 4:008/31/2012 0:008/31/2012 23:009/1/2012 4:009/1/2012 9:009/1/2012 10:009/1/2012 12:009/1/2012 13:009/1/2012 14:009/1/2012 15:009/1/2012 16:009/1/2012 17:009/1/2012 18:009/1/2012 19:009/1/2012 20:009/1/2012 21:009/1/2012 22:009/2/2012 0:009/2/2012 1:009/2/2012 2:009/2/2012 20:009/2/2012 23:009/3/2012 0:009/3/2012 4:009/6/2012 20:009/7/2012 0:009/7/2012 1:009/7/2012 3:009/7/2012 4:009/9/2012 5:009/10/2012 20:009/10/2012 21:009/10/2012 22:009/10/2012 23:009/11/2012 0:009/11/2012 1:009/11/2012 2:009/11/2012 3:009/11/2012 4:009/11/2012 5:009/11/2012 21:009/11/2012 22:009/11/2012 23:009/12/2012 0:009/12/2012 1:009/12/2012 2:009/12/2012 3:009/12/2012 4:009/12/2012 5:009/12/2012 6:009/12/2012 7:009/12/2012 8:009/12/2012 9:009/12/2012 11:009/12/2012 21:009/13/2012 3:009/13/2012 4:009/13/2012 5:009/13/2012 20:009/13/2012 23:009/14/2012 0:009/14/2012 1:009/14/2012 2:009/14/2012 3:009/14/2012 4:009/15/2012 22:009/15/2012 23:009/16/2012 0:009/16/2012 1:009/16/2012 2:009/16/2012 3:009/16/2012 4:009/16/2012 5:009/16/2012 6:009/16/2012 7:009/16/2012 8:009/16/2012 15:009/16/2012 16:009/16/2012 17:009/16/2012 18:009/16/2012 20:009/16/2012 21:009/16/2012 22:009/16/2012 23:009/17/2012 0:009/17/2012 1:009/17/2012 2:009/17/2012 14:009/17/2012 15:009/17/2012 17:009/18/2012 2:009/19/2012 18:009/19/2012 19:009/19/2012 20:009/19/2012 21:009/19/2012 22:009/19/2012 23:009/20/2012 0:009/20/2012 1:009/20/2012 2:009/20/2012 3:009/20/2012 4:009/20/2012 5:009/20/2012 6:009/20/2012 7:009/20/2012 8:009/20/2012 9:009/20/2012 10:009/20/2012 11:009/20/2012 12:009/20/2012 15:009/20/2012 16:009/20/2012 17:009/20/2012 18:009/20/2012 19:009/20/2012 21:009/20/2012 22:009/24/2012 2:009/24/2012 3:009/25/2012 19:009/27/2012 3:009/27/2012 4:009/27/2012 5:009/27/2012 6:009/27/2012 7:009/27/2012 8:009/27/2012 19:009/27/2012 21:009/27/2012 22:009/27/2012 23:009/28/2012 0:009/28/2012 3:009/28/2012 4:0010/2/2012 4:0010/2/2012 22:0010/2/2012 23:0010/3/2012 0:0010/3/2012 1:0010/3/2012 2:0010/3/2012 3:0010/3/2012 4:0010/5/2012 2:0010/5/2012 3:0010/5/2012 4:0010/5/2012 5:0010/7/2012 4:0010/8/2012 3:0010/8/2012 4:0010/8/2012 5:0010/8/2012 9:0010/8/2012 22:0010/8/2012 23:0010/9/2012 0:0010/9/2012 1:0010/9/2012 2:0010/9/2012 3:0010/9/2012 4:0010/9/2012 8:0010/9/2012 9:0010/9/2012 10:0010/12/2012 18:0010/12/2012 19:0010/12/2012 20:0010/12/2012 21:0010/12/2012 22:0010/13/2012 5:0010/16/2012 20:0010/16/2012 21:0010/16/2012 22:0010/16/2012 23:0010/17/2012 0:0010/17/2012 1:0010/17/2012 2:0010/17/2012 7:0010/20/2012 19:0010/22/2012 5:0010/22/2012 6:0010/22/2012 19:0010/22/2012 21:0010/22/2012 23:0010/23/2012 0:0010/23/2012 1:0010/23/2012 2:0010/23/2012 3:0010/23/2012 4:0010/23/2012 5:0010/23/2012 23:0010/24/2012 0:0010/24/2012 1:0010/24/2012 2:0010/24/2012 3:0010/24/2012 4:0010/24/2012 5:0010/24/2012 6:0010/24/2012 7:0010/24/2012 8:0010/25/2012 19:0010/25/2012 20:0010/25/2012 21:0010/25/2012 22:0010/25/2012 23:0010/26/2012 0:0010/26/2012 3:0010/26/2012 4:0010/26/2012 5:0010/26/2012 6:0010/26/2012 7:0010/26/2012 8:0010/26/2012 9:0010/26/2012 10:0010/26/2012 11:0010/26/2012 12:0010/26/2012 13:0010/26/2012 14:0010/26/2012 15:0010/26/2012 16:0011/6/2012 1:0011/6/2012 2:0011/6/2012 3:0011/6/2012 18:0011/6/2012 19:0011/6/2012 20:0011/6/2012 21:0011/6/2012 22:0011/6/2012 23:0011/7/2012 0:0011/7/2012 1:0011/7/2012 2:0011/7/2012 3:0011/7/2012 4:0011/7/2012 5:0011/7/2012 22:0011/9/2012 2:0011/9/2012 3:0011/9/2012 4:0011/10/2012 7:0011/10/2012 8:0011/10/2012 9:0011/10/2012 21:0011/11/2012 14:0011/11/2012 19:0011/11/2012 20:0011/11/2012 22:0011/11/2012 23:0011/12/2012 3:0011/12/2012 4:0011/12/2012 5:0011/13/2012 17:0011/13/2012 18:0011/13/2012 19:0011/13/2012 20:0011/13/2012 21:0011/13/2012 22:0011/13/2012 23:0011/14/2012 0:0011/14/2012 1:0011/14/2012 2:0011/14/2012 3:0011/14/2012 4:0011/14/2012 5:0011/14/2012 6:0011/14/2012 7:0011/14/2012 8:0011/14/2012 9:0011/14/2012 10:0011/14/2012 11:0011/14/2012 14:0011/14/2012 15:0011/14/2012 18:0011/14/2012 19:0011/14/2012 20:0011/14/2012 21:0011/14/2012 22:0011/14/2012 23:0011/15/2012 0:0011/15/2012 4:0011/15/2012 18:0011/15/2012 19:0011/15/2012 20:0011/15/2012 21:0011/15/2012 22:0011/15/2012 23:0011/16/2012 0:0011/16/2012 1:0011/16/2012 2:0011/16/2012 3:0011/16/2012 4:0011/16/2012 5:0011/17/2012 0:0011/17/2012 1:0011/17/2012 3:0011/17/2012 4:0011/17/2012 5:0011/17/2012 6:0011/17/2012 17:0011/17/2012 19:0011/17/2012 20:0011/17/2012 21:0011/17/2012 22:0011/17/2012 23:0011/18/2012 0:0011/18/2012 1:0011/18/2012 2:0011/18/2012 3:0011/18/2012 4:0011/18/2012 5:0011/19/2012 6:0011/19/2012 7:0011/19/2012 9:0011/19/2012 12:0011/19/2012 17:0011/19/2012 20:0011/19/2012 22:0011/22/2012 1:0011/22/2012 2:0011/22/2012 3:0011/22/2012 4:0011/22/2012 5:0011/22/2012 6:0011/22/2012 9:0011/22/2012 10:0011/23/2012 0:0011/25/2012 2:0011/25/2012 17:0011/25/2012 18:0011/25/2012 19:0011/26/2012 10:0011/26/2012 11:0011/26/2012 13:0011/26/2012 14:0011/26/2012 15:0011/26/2012 16:0011/26/2012 17:0011/26/2012 18:0011/26/2012 19:0011/26/2012 20:0011/26/2012 21:0011/26/2012 22:0011/26/2012 23:0011/27/2012 0:0011/27/2012 1:0011/27/2012 16:0011/27/2012 17:0011/27/2012 18:0011/27/2012 19:0011/27/2012 20:0011/29/2012 0:0011/29/2012 1:0011/29/2012 2:0011/29/2012 3:0011/29/2012 4:0011/30/2012 0:0011/30/2012 1:0011/30/2012 2:0011/30/2012 3:0011/30/2012 4:0011/30/2012 5:0012/1/2012 0:0012/3/2012 6:0012/11/2012 15:0012/11/2012 16:0012/11/2012 17:0012/11/2012 18:0012/11/2012 19:0012/11/2012 20:0012/11/2012 21:0012/11/2012 22:0012/11/2012 23:0012/12/2012 0:0012/12/2012 1:0012/12/2012 2:0012/12/2012 3:0012/12/2012 4:0012/12/2012 5:0012/12/2012 6:0012/13/2012 0:0012/13/2012 1:0012/13/2012 2:0012/13/2012 3:0012/15/2012 0:0012/15/2012 1:0012/15/2012 2:0012/15/2012 3:0012/15/2012 4:0012/15/2012 5:0012/15/2012 6:0012/15/2012 7:0012/15/2012 8:0012/15/2012 9:0012/15/2012 13:0012/15/2012 18:0012/15/2012 20:0012/24/2012 7:0012/24/2012 8:0012/24/2012 9:0012/24/2012 18:0012/25/2012 15:0012/25/2012 16:0012/25/2012 17:0012/25/2012 21:0012/25/2012 22:0012/25/2012 23:0012/26/2012 0:0012/26/2012 1:0012/26/2012 2:0012/26/2012 3:0012/26/2012 4:0012/26/2012 5:0012/26/2012 6:0012/28/2012 10:0012/29/2012 1:0012/29/2012 2:0012/30/2012 20:00 to numeric

In [39]:
df.head(2)

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [45]:
#Q18. What is the Minimum & Maximum value of each column against each 'Weather Conditon' ?
df['Weather_Condition'].max()

'Thunderstorms,Rain,Fog'

In [46]:
df['Weather_Condition'].min()

'Clear'

In [48]:
#Q19. Show all the Records where Weather Condition is Fog ?
df[df.Weather_Condition=='Fog']

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,1/1/2012 5:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,1/1/2012 6:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,12/29/2012 4:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,12/29/2012 5:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,12/29/2012 6:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,12/29/2012 7:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,12/29/2012 10:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [51]:
# Find all instances when 'Weather is Clear' or 'Visibility is above 40' ?
df[(df['Weather_Condition']=='Clear') | (df['Visibility_km']>40) ]

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [53]:
#Q21. Find all instances when : A. 'Weather is Clear' and 'Relative Humidity is greater than 50' . or B. 'Visibility is above 40' .
df[(df['Weather_Condition']=='Clear') &(df['Rel_Hum_%']>50)|(df['Visibility_km']>40) ]

,Date/Time,Temp_C,Dew_Point_Temp_C,Rel_Hum_%,Wind_Speed_km/h,Visibility_km,Press_kPa,Weather_Condition
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear